name: tmdb_api
description: Dart client-side API package for TMDB.org API (https://www.themoviedb.org/).
version: 2.0.0-nullsafety
# author: Ratakondala Arun<ratakondalaarun@gmail.com>
homepage: https://github.com/RatakondalaArun/tmdb_api.git

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  colorize: ^3.0.0
  http: ^0.13.4

dev_dependencies:
  lint: ^1.7.2
  test: ^1.18.2
