name: tmdb_api
description: Dart client-side API package for TMDB.org API (https://www.themoviedb.org/).
version: 2.2.0
homepage: https://github.com/RatakondalaArun/tmdb_api.git
issue_tracker: https://github.com/RatakondalaArun/tmdb_api/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  colorize: ^3.0.0
  dio: ^5.3.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.4
